language: python
python:
  - 2.7
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
before_install:
  - ssh-keygen -t rsa -f ~/.ssh/id_rsa_localhost -N ""
  - cat ~/.ssh/id_rsa_localhost.pub >> ~/.ssh/authorized_keys
  - echo -e "Host localhost 127.0.0.1\nStrictHostKeyChecking no\nIdentityFile ~/.ssh/id_rsa_localhost" >> ~/.ssh/config
install: 
  - sudo apt-get -y install libevent-dev
  - sudo pip install -r config/base_requirements.txt
  - sudo pip install -r config/app_requirements.txt
  - fab deploy_to_server -H 127.0.0.1 -i ~/.ssh/id_rsa_localhost
# command to run tests, e.g. python setup.py test
script: nosetests -w tests --tc www_port:80 --tc vagrant_enabled:no
