language: python
python:
  - 2.7
script: make travis_test
addons:
  postgresql: "9.3"
after_failure: 
  - sudo supervisorctl status
  - tail -100 /var/log/mailboxer-wsgi.log
  - tail -100 /var/log/mailboxer-smtpd.log
  
