language: python
sudo: false
python:
  - 3.4
addons:
  postgresql: "9.4"
services:
  - redis-server
install:
  - pip install virtualenv
  - createdb -E utf-8 mailboxer
  - python manage.py db upgrade
script: python manage.py travis-test
