language: python
python:
  - 2.7
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
before_install:
  - ssh-keygen -t rsa -f ~/.ssh/id_rsa_localhost -N ""
  - cat ~/.ssh/id_rsa_localhost.pub >> ~/.ssh/authorized_keys
  - echo -e "Host localhost 127.0.0.1\nStrictHostKeyChecking no\nIdentityFile ~/.ssh/id_rsa_localhost" >> ~/.ssh/config
install: 
  - sudo easy_install nose fabric confetti jinja2 fabtools
# command to run tests, e.g. python setup.py test
script: fab deploy_to_server -H 127.0.0.1 -i ~/.ssh/id_rsa_localhost
