jobs:
  include:
    - stage: build
      language: rust
      rust: stable
      script:
        - cargo test
    - stage: test
      sudo: required
      language: python
      python: 3.6
      services:
        - docker
      install:
        - docker version
        - docker build -t getslash/mailboxer:testing -f docker/Dockerfile .
        - docker-compose -p mailboxer -f docker/docker-compose.yml -f docker/docker-compose-testing-override.yml up -d
        - pip install pipenv
        - pipenv install -d
      script:
        - MAILBOXER_SPAWN_SERVER=false pipenv run pytest tests && python scripts/travis_docker_publish.py
      after_failure:
        - docker ps
        - docker logs mailboxer_backend_1
