"""Add indices

Revision ID: 0af40d5451e5
Revises: 60381cf94c20
Create Date: 2016-08-24 09:39:30.842941

"""

# revision identifiers, used by Alembic.
revision = '0af40d5451e5'
down_revision = '60381cf94c20'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_mailbox_read_timestamp', 'email', ['mailbox_id', 'read', 'timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mailbox_read_timestamp', table_name='email')
    ### end Alembic commands ###
